<html>
<head>
<title>TestNG:  Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>8/3/0</td>
</tr><tr>
<td>Started on:</td><td>Sun Jun 14 22:28:04 IDT 2020</td>
</tr>
<tr><td>Total time:</td><td>39 seconds (39197 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='TestCases.Login_Test.T01_successfulLogin()'><b>T01_successfulLogin</b><br>Test class: TestCases.Login_Test<br>Parameters: standard_user, secret_sauce, valid credentials</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	expected [Products] but found [Products_123123]
	at TestCases.Login_Test.T01_successfulLogin(Login_Test.java:67)
	at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1591916281", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1591916281'><pre>java.lang.AssertionError: The following asserts failed:
	expected [Products] but found [Products_123123]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at TestCases.Login_Test.T01_successfulLogin(Login_Test.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>TestCases.Login_Test@10b48321</td></tr>
<tr>
<td title='TestCases.Checkout_Test.T02_selectSingleItem()'><b>T02_selectSingleItem</b><br>Test class: TestCases.Checkout_Test</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	expected [1] but found [3]
	at TestCases.Checkout_Test.T02_selectSingleItem(Checkout_Test.java:67)
	at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace371397455", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace371397455'><pre>java.lang.AssertionError: The following asserts failed:
	expected [1] but found [3]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at TestCases.Checkout_Test.T02_selectSingleItem(Checkout_Test.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>TestCases.Checkout_Test@6b67034</td></tr>
<tr>
<td title='TestCases.Checkout_Test.T03_continueToCheckout()'><b>T03_continueToCheckout</b><br>Test class: TestCases.Checkout_Test</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	expected [1] but found [3],
	expected [15.99] but found [15.99_123]
	at TestCases.Checkout_Test.T03_continueToCheckout(Checkout_Test.java:80)
	at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1917082298", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1917082298'><pre>java.lang.AssertionError: The following asserts failed:
	expected [1] but found [3],
	expected [15.99] but found [15.99_123]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at TestCases.Checkout_Test.T03_continueToCheckout(Checkout_Test.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>3</td>
<td>TestCases.Checkout_Test@6b67034</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='TestCases.Login_Test.T01_invalidLoginAttempts()'><b>T01_invalidLoginAttempts</b><br>Test class: TestCases.Login_Test<br>Parameters: Daniel, aaaa, invalid credentials</td>
<td></td>
<td>2</td>
<td>TestCases.Login_Test@10b48321</td></tr>
<tr>
<td title='TestCases.Login_Test.T01_invalidLoginAttempts()'><b>T01_invalidLoginAttempts</b><br>Test class: TestCases.Login_Test<br>Parameters: bbbb, secret_sauce, only username is invalid</td>
<td></td>
<td>2</td>
<td>TestCases.Login_Test@10b48321</td></tr>
<tr>
<td title='TestCases.Login_Test.T01_invalidLoginAttempts()'><b>T01_invalidLoginAttempts</b><br>Test class: TestCases.Login_Test<br>Parameters: standard_user, cccc, only password is invalid</td>
<td></td>
<td>2</td>
<td>TestCases.Login_Test@10b48321</td></tr>
<tr>
<td title='TestCases.Login_Test.T01_invalidLoginAttempts()'><b>T01_invalidLoginAttempts</b><br>Test class: TestCases.Login_Test<br>Parameters: , secret_sauce, username is missing</td>
<td></td>
<td>2</td>
<td>TestCases.Login_Test@10b48321</td></tr>
<tr>
<td title='TestCases.Login_Test.T01_invalidLoginAttempts()'><b>T01_invalidLoginAttempts</b><br>Test class: TestCases.Login_Test<br>Parameters: standard_user, , password is missing</td>
<td></td>
<td>2</td>
<td>TestCases.Login_Test@10b48321</td></tr>
<tr>
<td title='TestCases.Checkout_Test.T01_validLogin()'><b>T01_validLogin</b><br>Test class: TestCases.Checkout_Test</td>
<td></td>
<td>0</td>
<td>TestCases.Checkout_Test@6b67034</td></tr>
<tr>
<td title='TestCases.Checkout_Test.T04_checkout_StepOne()'><b>T04_checkout_StepOne</b><br>Test class: TestCases.Checkout_Test</td>
<td></td>
<td>6</td>
<td>TestCases.Checkout_Test@6b67034</td></tr>
<tr>
<td title='TestCases.Checkout_Test.T05_checkout_StepTwo()'><b>T05_checkout_StepTwo</b><br>Test class: TestCases.Checkout_Test</td>
<td></td>
<td>0</td>
<td>TestCases.Checkout_Test@6b67034</td></tr>
</table><p>
</body>
</html>