<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MeitalDaniel-PC" ignored="0" name="Test" tests="11" failures="3" timestamp="2020-06-14T22:28:44 IDT" time="39.197" errors="0">
  <testcase name="T01_invalidLoginAttempts" time="2.317" classname="TestCases.Login_Test"/>
  <testcase name="T01_invalidLoginAttempts" time="2.481" classname="TestCases.Login_Test"/>
  <testcase name="T01_invalidLoginAttempts" time="2.28" classname="TestCases.Login_Test"/>
  <testcase name="T01_invalidLoginAttempts" time="2.267" classname="TestCases.Login_Test"/>
  <testcase name="T01_invalidLoginAttempts" time="2.316" classname="TestCases.Login_Test"/>
  <testcase name="T01_successfulLogin" time="0.863" classname="TestCases.Login_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Products] but found [Products_123123]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Products] but found [Products_123123]
at TestCases.Login_Test.T01_successfulLogin(Login_Test.java:67)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- T01_successfulLogin -->
  <testcase name="T01_validLogin" time="0.938" classname="TestCases.Checkout_Test"/>
  <testcase name="T02_selectSingleItem" time="0.361" classname="TestCases.Checkout_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [3]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [3]
at TestCases.Checkout_Test.T02_selectSingleItem(Checkout_Test.java:67)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- T02_selectSingleItem -->
  <testcase name="T03_continueToCheckout" time="3.179" classname="TestCases.Checkout_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [3],
	expected [15.99] but found [15.99_123]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [3],
expected [15.99] but found [15.99_123]
at TestCases.Checkout_Test.T03_continueToCheckout(Checkout_Test.java:80)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- T03_continueToCheckout -->
  <testcase name="T04_checkout_StepOne" time="6.65" classname="TestCases.Checkout_Test"/>
  <testcase name="T05_checkout_StepTwo" time="0.277" classname="TestCases.Checkout_Test"/>
</testsuite> <!-- Test -->
